export const globalDistricts = [
  { districtId: 1, districtName: "Açores" },
  { districtId: 2, districtName: "Aveiro" },
  { districtId: 3, districtName: "Beja" },
  { districtId: 4, districtName: "Braga" },
  { districtId: 5, districtName: "Bragança" },
  { districtId: 6, districtName: "Castelo Branco" },
  { districtId: 7, districtName: "Coimbra" },
  { districtId: 8, districtName: "Évora" },
  { districtId: 9, districtName: "Faro" },
  { districtId: 10, districtName: "Guarda" },
  { districtId: 11, districtName: "Leiria" },
  { districtId: 12, districtName: "Lisboa" },
  { districtId: 13, districtName: "Madeira" },
  { districtId: 14, districtName: "Portalegre" },
  { districtId: 15, districtName: "Porto" },
  { districtId: 16, districtName: "Santarém" },
  { districtId: 17, districtName: "Setúbal" },
  { districtId: 18, districtName: "Viana do Castelo" },
  { districtId: 19, districtName: "Vila Real" },
  { districtId: 20, districtName: "Viseu" },
]
