export const globalDistricts = [
  { districtId: 1, name: "Açores" },
  { districtId: 2, name: "Aveiro" },
  { districtId: 3, name: "Beja" },
  { districtId: 4, name: "Braga" },
  { districtId: 5, name: "Bragança" },
  { districtId: 6, name: "Castelo Branco" },
  { districtId: 7, name: "Coimbra" },
  { districtId: 8, name: "Évora" },
  { districtId: 9, name: "Faro" },
  { districtId: 10, name: "Guarda" },
  { districtId: 11, name: "Leiria" },
  { districtId: 12, name: "Lisboa" },
  { districtId: 13, name: "Madeira" },
  { districtId: 14, name: "Portalegre" },
  { districtId: 15, name: "Porto" },
  { districtId: 16, name: "Santarém" },
  { districtId: 17, name: "Setúbal" },
  { districtId: 18, name: "Viana do Castelo" },
  { districtId: 19, name: "Vila Real" },
  { districtId: 20, name: "Viseu" },
]
